name: Create Tag an Release

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/pvpc_hourly_pricing/manifest.json'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version from JSON
        id: get_version
        run: |
          VERSION=$(jq -r '.version' custom_components/pvpc_hourly_pricing/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" =~ [a-zA-Z] ]]; then
            echo "IS_PRE_RELEASE=true" >> $GITHUB_ENV
            echo "Modo detectado: Pre-release (Beta)"
          else
            echo "IS_PRE_RELEASE=false" >> $GITHUB_ENV
            echo "Modo detectado: Stable Version"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          prerelease: ${{ env.IS_PRE_RELEASE }}
          generate_release_notes: true
          fail_on_unmatched_files: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Wait for 10 seconds"
        run: sleep 10s
        shell: bash

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/pvpc_hourly_pricing"
          zip pvpc_hourly_pricing.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: ${{ github.workspace }}/custom_components/pvpc_hourly_pricing/pvpc_hourly_pricing.zip
          tag_name: ${{ env.VERSION }}
